<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
DB::table('municipios')->insert(['nombre'=>'Guatemala','codigo'=>'01','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Santa Catarina Pinula','codigo'=>'02','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San José Pinula','codigo'=>'03','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San José del Golfo','codigo'=>'04','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Palencia','codigo'=>'05','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Chinautla','codigo'=>'06','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Ayampuc','codigo'=>'07','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Mixco','codigo'=>'08','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Sacatepéquez','codigo'=>'09','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San Juan Sacatepéquez','codigo'=>'10','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'San Raymundo','codigo'=>'11','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Chuarrancho','codigo'=>'12','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Fraijanes','codigo'=>'13','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Amatitlán','codigo'=>'14','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Villa Nueva','codigo'=>'15','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Villa Canales','codigo'=>'16','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Petapa','codigo'=>'17','departamento_id'=>'1']);
DB::table('municipios')->insert(['nombre'=>'Guastatoya','codigo'=>'01','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'Morazán','codigo'=>'02','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'San Agustín Acasaguastlán','codigo'=>'03','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'San Cristóbal Acasaguastlán','codigo'=>'04','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'El Jícaro','codigo'=>'05','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'Sansare','codigo'=>'06','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'Sanarate','codigo'=>'07','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'San Antonio la Paz','codigo'=>'08','departamento_id'=>'2']);
DB::table('municipios')->insert(['nombre'=>'Antigua Guatemala','codigo'=>'01','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Jocotenango','codigo'=>'02','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Pastores','codigo'=>'03','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Sumpango','codigo'=>'04','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Santo Domingo Xenacoj','codigo'=>'05','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Santiago Sacatepéquez','codigo'=>'06','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'San Bartolomé Milpas Altas','codigo'=>'07','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'San Lucas Sacatepéquez','codigo'=>'08','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Santa Lucía Milpas Altas','codigo'=>'09','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Magdalena Milpas Altas','codigo'=>'10','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Santa María de Jesús','codigo'=>'11','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Ciudad Vieja','codigo'=>'12','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Dueñas','codigo'=>'13','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Alotenango','codigo'=>'14','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Aguas Calientes','codigo'=>'15','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Santa Catarina Barahona','codigo'=>'16','departamento_id'=>'3']);
DB::table('municipios')->insert(['nombre'=>'Chimaltenango','codigo'=>'01','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'San José Poaquil','codigo'=>'02','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'San Martín Jilotepeque','codigo'=>'03','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Comalapa','codigo'=>'04','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Santa Apolonia','codigo'=>'05','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Tecpán Guatemala','codigo'=>'06','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Patzún','codigo'=>'07','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Pochuta','codigo'=>'08','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Patzicía','codigo'=>'09','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz Balanyá','codigo'=>'10','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Acatenango','codigo'=>'11','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Yepocapa','codigo'=>'12','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'San Andrés Itzapa','codigo'=>'13','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Parramos','codigo'=>'14','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Zaragoza','codigo'=>'15','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'El Tejar','codigo'=>'16','departamento_id'=>'4']);
DB::table('municipios')->insert(['nombre'=>'Escuintla','codigo'=>'01','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Santa Lucía Cotzumalguapa','codigo'=>'02','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'La Democracia','codigo'=>'03','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Siquinalá','codigo'=>'04','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Masagua','codigo'=>'05','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Tiquisate','codigo'=>'06','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'La Gomera','codigo'=>'07','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Guanagazapa','codigo'=>'08','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'San José','codigo'=>'09','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Iztapa','codigo'=>'10','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Palín','codigo'=>'11','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'San Vicente Pacaya','codigo'=>'12','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Nueva Concepción','codigo'=>'13','departamento_id'=>'5']);
DB::table('municipios')->insert(['nombre'=>'Cuilapa','codigo'=>'01','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Barberena','codigo'=>'02','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Santa Rosa de Lima','codigo'=>'03','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Casillas','codigo'=>'04','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'San Rafael las Flores','codigo'=>'05','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Oratorio','codigo'=>'06','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'San Juan Tecuaco','codigo'=>'07','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Chiquimulilla','codigo'=>'08','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Taxisco','codigo'=>'09','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Santa María Ixhuatán','codigo'=>'10','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Guazacapán','codigo'=>'11','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz Naranjo','codigo'=>'12','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Pueblo Nuevo Viñas','codigo'=>'13','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Nueva Santa Rosa','codigo'=>'14','departamento_id'=>'6']);
DB::table('municipios')->insert(['nombre'=>'Sololá','codigo'=>'01','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San José Chacayá','codigo'=>'02','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa María Visitación','codigo'=>'03','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa Lucía Utatlán','codigo'=>'04','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Nahualá','codigo'=>'05','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa Catarina Ixtahuacán','codigo'=>'06','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa Clara la Laguna','codigo'=>'07','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Concepción','codigo'=>'08','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Andrés Semetabaj','codigo'=>'09','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Panajachel','codigo'=>'10','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa Catarina Palopó','codigo'=>'11','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Palopó','codigo'=>'12','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Lucas Tolimán','codigo'=>'13','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz la Laguna','codigo'=>'14','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Pablo la Laguna','codigo'=>'15','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Marcos la Laguna','codigo'=>'16','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Juan la Laguna','codigo'=>'17','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'San Pedro la Laguna','codigo'=>'18','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Santiago Atitlán','codigo'=>'19','departamento_id'=>'7']);
DB::table('municipios')->insert(['nombre'=>'Totonicapán','codigo'=>'01','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'San Cristóbal Totonicapán','codigo'=>'02','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'San Francisco el Alto','codigo'=>'03','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'San Andrés Xecul','codigo'=>'04','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'Momostenango','codigo'=>'05','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'Santa María Chiquimula','codigo'=>'06','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'Santa Lucía la Reforma','codigo'=>'07','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'San Bartolo','codigo'=>'08','departamento_id'=>'8']);
DB::table('municipios')->insert(['nombre'=>'Quetzaltenango','codigo'=>'01','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Salcajá','codigo'=>'02','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Olintepeque','codigo'=>'03','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'San Carlos Sija','codigo'=>'04','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Sibilia','codigo'=>'05','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Cabricán','codigo'=>'06','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Cajolá','codigo'=>'07','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Siguilá','codigo'=>'08','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Ostuncalco','codigo'=>'09','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'San Mateo','codigo'=>'10','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Concepción Chiquirichapa','codigo'=>'11','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'San Martín Sacatepéquez','codigo'=>'12','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Almolonga','codigo'=>'13','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Cantel','codigo'=>'14','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Huitán','codigo'=>'15','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Zunil','codigo'=>'16','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Colomba','codigo'=>'17','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'San Francisco la Unión','codigo'=>'18','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'El Palmar','codigo'=>'19','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Coatepeque','codigo'=>'20','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Génova','codigo'=>'21','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Flores Costa Cuca','codigo'=>'22','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'La Esperanza','codigo'=>'23','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Palestina de los Altos','codigo'=>'24','departamento_id'=>'9']);
DB::table('municipios')->insert(['nombre'=>'Mazatenango','codigo'=>'01','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Cuyotenango','codigo'=>'02','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Francisco Zapotitlán','codigo'=>'03','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Bernardino','codigo'=>'04','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San José el Idolo','codigo'=>'05','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Santo Domingo Suchitepéquez','codigo'=>'06','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Lorenzo','codigo'=>'07','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Samayac','codigo'=>'08','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Pablo Jocopilas','codigo'=>'09','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Suchitepéquez','codigo'=>'10','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Panán','codigo'=>'11','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Gabriel','codigo'=>'12','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Chicacao','codigo'=>'13','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Patulul','codigo'=>'14','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Santa Bárbara','codigo'=>'15','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San Juan Bautista','codigo'=>'16','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Santo Tomás la Unión','codigo'=>'17','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Zunilito','codigo'=>'18','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Pueblo Nuevo','codigo'=>'19','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Río Bravo','codigo'=>'20','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'San José La Máquina','codigo'=>'21','departamento_id'=>'10']);
DB::table('municipios')->insert(['nombre'=>'Retalhuleu','codigo'=>'01','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'San Sebastián','codigo'=>'02','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz Muluá','codigo'=>'03','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'San Martín Zapotitlán','codigo'=>'04','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'San Felipe','codigo'=>'05','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'San Andrés Villa Seca','codigo'=>'06','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'Champerico','codigo'=>'07','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'Nuevo San Carlos','codigo'=>'08','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'El Asintal','codigo'=>'09','departamento_id'=>'11']);
DB::table('municipios')->insert(['nombre'=>'San Marcos','codigo'=>'01','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Sacatepéquez','codigo'=>'02','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Sacatepéquez','codigo'=>'03','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Comitancillo','codigo'=>'04','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Ixtahuacán','codigo'=>'05','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Concepción Tutuapa','codigo'=>'06','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Tacaná','codigo'=>'07','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Sibinal','codigo'=>'08','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Tajumulco','codigo'=>'09','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Tejutla','codigo'=>'10','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Rafael Pié de la Cuesta','codigo'=>'11','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Nuevo Progreso','codigo'=>'12','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'El Tumbador','codigo'=>'13','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'El Rodeo','codigo'=>'14','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Malacatán','codigo'=>'15','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Catarina','codigo'=>'16','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Ayutla','codigo'=>'17','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Ocós','codigo'=>'18','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Pablo','codigo'=>'19','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'El Quetzal','codigo'=>'20','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'La Reforma','codigo'=>'21','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Pajapita','codigo'=>'22','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Ixchiguán','codigo'=>'23','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San José Ojetenán','codigo'=>'24','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Cristóbal Cucho','codigo'=>'25','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Sipacapa','codigo'=>'26','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Esquipulas Palo Gordo','codigo'=>'27','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Río Blanco','codigo'=>'28','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'San Lorenzo','codigo'=>'29','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'La Blanca','codigo'=>'30','departamento_id'=>'12']);
DB::table('municipios')->insert(['nombre'=>'Huehuetenango','codigo'=>'01','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Chiantla','codigo'=>'02','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Malacatancito','codigo'=>'03','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Cuilco','codigo'=>'04','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Nentón','codigo'=>'05','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Necta','codigo'=>'06','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Jacaltenango','codigo'=>'07','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Soloma','codigo'=>'08','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Ixtahuacán','codigo'=>'09','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Santa Bárbara','codigo'=>'10','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'La Libertad','codigo'=>'11','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'La Democracia','codigo'=>'12','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Acatán','codigo'=>'13','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Rafael la Independencia','codigo'=>'14','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Todos Santos Cuchumatán','codigo'=>'15','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Juan Atitán','codigo'=>'16','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Santa Eulalia','codigo'=>'17','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Mateo Ixtatán','codigo'=>'18','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Colotenango','codigo'=>'19','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Sebastián Huehuetenango','codigo'=>'20','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Tectitán','codigo'=>'21','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Concepción Huista','codigo'=>'22','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Juan Ixcoy','codigo'=>'23','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Huista','codigo'=>'24','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Sebastián Coatán','codigo'=>'25','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Barillas','codigo'=>'26','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Aguacatán','codigo'=>'27','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Rafael Petzal','codigo'=>'28','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'San Gaspar Ixchil','codigo'=>'29','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Santiago Chimaltenango','codigo'=>'30','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Santa Ana Huista','codigo'=>'31','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Unión Cantinil','codigo'=>'32','departamento_id'=>'13']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz del Quiché','codigo'=>'01','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Chiché','codigo'=>'02','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Chinique','codigo'=>'03','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Zacualpa','codigo'=>'04','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Chajul','codigo'=>'05','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Chichicastenango','codigo'=>'06','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Patzité','codigo'=>'07','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'San Antonio Ilotenango','codigo'=>'08','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Jocopilas','codigo'=>'09','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Cunén','codigo'=>'10','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'San Juan Cotzal','codigo'=>'11','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Joyabaj','codigo'=>'12','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Nebaj','codigo'=>'13','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'San Andrés Sajcabajá','codigo'=>'14','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Uspantán','codigo'=>'15','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Sacapulas','codigo'=>'16','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'San Bartolomé Jocotenango','codigo'=>'17','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Canillá','codigo'=>'18','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Chicamán','codigo'=>'19','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Ixcán','codigo'=>'20','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Pachalum','codigo'=>'21','departamento_id'=>'14']);
DB::table('municipios')->insert(['nombre'=>'Salamá','codigo'=>'01','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'San Miguel Chicaj','codigo'=>'02','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'Rabinal','codigo'=>'03','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'Cubulco','codigo'=>'04','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'Granados','codigo'=>'05','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'El Chol','codigo'=>'06','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'San Jerónimo','codigo'=>'07','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'Purulhá','codigo'=>'08','departamento_id'=>'15']);
DB::table('municipios')->insert(['nombre'=>'Cobán','codigo'=>'01','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Santa Cruz Verapaz','codigo'=>'02','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'San Cristóbal Verapaz','codigo'=>'03','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Tactic','codigo'=>'04','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Tamahú','codigo'=>'05','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Tucurú','codigo'=>'06','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Panzós','codigo'=>'07','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Senahú','codigo'=>'08','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Carchá','codigo'=>'09','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'San Juan Chamelco','codigo'=>'10','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Lanquín','codigo'=>'11','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Cahabón','codigo'=>'12','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Chisec','codigo'=>'13','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Chahal','codigo'=>'14','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Fray Bartolomé de las Casas','codigo'=>'15','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Santa Catalina la Tinta','codigo'=>'16','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Raxruhá','codigo'=>'17','departamento_id'=>'16']);
DB::table('municipios')->insert(['nombre'=>'Flores','codigo'=>'01','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'San José','codigo'=>'02','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'San Benito','codigo'=>'03','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'San Andrés','codigo'=>'04','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'La Libertad','codigo'=>'05','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'San Francisco','codigo'=>'06','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Santa Ana','codigo'=>'07','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Dolores','codigo'=>'08','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'San Luis','codigo'=>'09','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Sayaxché','codigo'=>'10','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Melchor de Mencos','codigo'=>'11','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Poptún','codigo'=>'12','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Las Cruces','codigo'=>'13','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'El Chal','codigo'=>'14','departamento_id'=>'17']);
DB::table('municipios')->insert(['nombre'=>'Puerto Barrios','codigo'=>'01','departamento_id'=>'18']);
DB::table('municipios')->insert(['nombre'=>'Livingston','codigo'=>'02','departamento_id'=>'18']);
DB::table('municipios')->insert(['nombre'=>'El Estor','codigo'=>'03','departamento_id'=>'18']);
DB::table('municipios')->insert(['nombre'=>'Morales','codigo'=>'04','departamento_id'=>'18']);
DB::table('municipios')->insert(['nombre'=>'Los Amates','codigo'=>'05','departamento_id'=>'18']);
DB::table('municipios')->insert(['nombre'=>'Zacapa','codigo'=>'01','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Estanzuela','codigo'=>'02','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Río Hondo','codigo'=>'03','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Gualán','codigo'=>'04','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Teculután','codigo'=>'05','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Usumatlán','codigo'=>'06','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Cabañas','codigo'=>'07','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'San Diego','codigo'=>'08','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'La Unión','codigo'=>'09','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Huité','codigo'=>'10','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'San Jorge','codigo'=>'11','departamento_id'=>'19']);
DB::table('municipios')->insert(['nombre'=>'Chiquimula','codigo'=>'01','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'San José La Arada','codigo'=>'02','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'San Juan Ermita','codigo'=>'03','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Jocotán','codigo'=>'04','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Camotán','codigo'=>'05','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Olopa','codigo'=>'06','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Esquipulas','codigo'=>'07','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Concepción Las Minas','codigo'=>'08','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Quetzaltepeque','codigo'=>'09','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'San Jacinto','codigo'=>'10','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Ipala','codigo'=>'11','departamento_id'=>'20']);
DB::table('municipios')->insert(['nombre'=>'Jalapa','codigo'=>'01','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'San Pedro Pinula','codigo'=>'02','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'San Luis Jilotepeque','codigo'=>'03','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'San Manuel Chaparrón','codigo'=>'04','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'San Carlos Alzatate','codigo'=>'05','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'Monjas','codigo'=>'06','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'Mataquescuintla','codigo'=>'07','departamento_id'=>'21']);
DB::table('municipios')->insert(['nombre'=>'Jutiapa','codigo'=>'01','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'El Progreso','codigo'=>'02','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Santa Catarina Mita','codigo'=>'03','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Agua Blanca','codigo'=>'04','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Asunción Mita','codigo'=>'05','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Yupiltepeque','codigo'=>'06','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Atescatempa','codigo'=>'07','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Jerez','codigo'=>'08','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'El Adelanto','codigo'=>'09','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Zapotitlán','codigo'=>'10','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Comapa','codigo'=>'11','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Jalpatagua','codigo'=>'12','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Conguaco','codigo'=>'13','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Moyuta','codigo'=>'14','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Pasaco','codigo'=>'15','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'San José Acatempa','codigo'=>'16','departamento_id'=>'22']);
DB::table('municipios')->insert(['nombre'=>'Quesada','codigo'=>'17','departamento_id'=>'22']);
        
    }
}
