<?php
/** frk */
namespace App\Constantes;

class DepartamentoMunicipio
{

public static $departamentos = [
    ['id'=>'1','nombre'=>'Guatemala','codigo'=>'01'],
    ['id'=>'2','nombre'=>'El Progreso','codigo'=>'02'],
    ['id'=>'3','nombre'=>'Sacatepéquez','codigo'=>'03'],
    ['id'=>'4','nombre'=>'Chimaltenango','codigo'=>'04'],
    ['id'=>'5','nombre'=>'Escuintla','codigo'=>'05'],
    ['id'=>'6','nombre'=>'Santa Rosa','codigo'=>'06'],
    ['id'=>'7','nombre'=>'Sololá','codigo'=>'07'],
    ['id'=>'8','nombre'=>'Totonicapán','codigo'=>'08'],
    ['id'=>'9','nombre'=>'Quetzaltenango','codigo'=>'09'],
    ['id'=>'10','nombre'=>'Suchitepéquez','codigo'=>'10'],
    ['id'=>'11','nombre'=>'Retalhuleu','codigo'=>'11'],
    ['id'=>'12','nombre'=>'San Marcos','codigo'=>'12'],
    ['id'=>'13','nombre'=>'Huehuetenango','codigo'=>'13'],
    ['id'=>'14','nombre'=>'Quiché','codigo'=>'14'],
    ['id'=>'15','nombre'=>'Baja Verapaz','codigo'=>'15'],
    ['id'=>'16','nombre'=>'Alta Verapaz','codigo'=>'16'],
    ['id'=>'17','nombre'=>'Petén','codigo'=>'17'],
    ['id'=>'18','nombre'=>'Izabal','codigo'=>'18'],
    ['id'=>'19','nombre'=>'Zacapa','codigo'=>'19'],
    ['id'=>'20','nombre'=>'Chiquimula','codigo'=>'20'],
    ['id'=>'21','nombre'=>'Jalapa','codigo'=>'21'],
    ['id'=>'22','nombre'=>'Jutiapa','codigo'=>'22'],

];

public static $municipios = [
    ['id'=>'1','nombre'=>'Guatemala','codigo'=>'01','departamento_id'=>'1'],
    ['id'=>'2','nombre'=>'Santa Catarina Pinula','codigo'=>'02','departamento_id'=>'1'],
    ['id'=>'3','nombre'=>'San José Pinula','codigo'=>'03','departamento_id'=>'1'],
    ['id'=>'4','nombre'=>'San José del Golfo','codigo'=>'04','departamento_id'=>'1'],
    ['id'=>'5','nombre'=>'Palencia','codigo'=>'05','departamento_id'=>'1'],
    ['id'=>'6','nombre'=>'Chinautla','codigo'=>'06','departamento_id'=>'1'],
    ['id'=>'7','nombre'=>'San Pedro Ayampuc','codigo'=>'07','departamento_id'=>'1'],
    ['id'=>'8','nombre'=>'Mixco','codigo'=>'08','departamento_id'=>'1'],
    ['id'=>'9','nombre'=>'San Pedro Sacatepéquez','codigo'=>'09','departamento_id'=>'1'],
    ['id'=>'10','nombre'=>'San Juan Sacatepéquez','codigo'=>'10','departamento_id'=>'1'],
    ['id'=>'11','nombre'=>'San Raymundo','codigo'=>'11','departamento_id'=>'1'],
    ['id'=>'12','nombre'=>'Chuarrancho','codigo'=>'12','departamento_id'=>'1'],
    ['id'=>'13','nombre'=>'Fraijanes','codigo'=>'13','departamento_id'=>'1'],
    ['id'=>'14','nombre'=>'Amatitlán','codigo'=>'14','departamento_id'=>'1'],
    ['id'=>'15','nombre'=>'Villa Nueva','codigo'=>'15','departamento_id'=>'1'],
    ['id'=>'16','nombre'=>'Villa Canales','codigo'=>'16','departamento_id'=>'1'],
    ['id'=>'17','nombre'=>'Petapa','codigo'=>'17','departamento_id'=>'1'],
    ['id'=>'18','nombre'=>'Guastatoya','codigo'=>'01','departamento_id'=>'2'],
    ['id'=>'19','nombre'=>'Morazán','codigo'=>'02','departamento_id'=>'2'],
    ['id'=>'20','nombre'=>'San Agustín Acasaguastlán','codigo'=>'03','departamento_id'=>'2'],
    ['id'=>'21','nombre'=>'San Cristóbal Acasaguastlán','codigo'=>'04','departamento_id'=>'2'],
    ['id'=>'22','nombre'=>'El Jícaro','codigo'=>'05','departamento_id'=>'2'],
    ['id'=>'23','nombre'=>'Sansare','codigo'=>'06','departamento_id'=>'2'],
    ['id'=>'24','nombre'=>'Sanarate','codigo'=>'07','departamento_id'=>'2'],
    ['id'=>'25','nombre'=>'San Antonio la Paz','codigo'=>'08','departamento_id'=>'2'],
    ['id'=>'26','nombre'=>'Antigua Guatemala','codigo'=>'01','departamento_id'=>'3'],
    ['id'=>'27','nombre'=>'Jocotenango','codigo'=>'02','departamento_id'=>'3'],
    ['id'=>'28','nombre'=>'Pastores','codigo'=>'03','departamento_id'=>'3'],
    ['id'=>'29','nombre'=>'Sumpango','codigo'=>'04','departamento_id'=>'3'],
    ['id'=>'30','nombre'=>'Santo Domingo Xenacoj','codigo'=>'05','departamento_id'=>'3'],
    ['id'=>'31','nombre'=>'Santiago Sacatepéquez','codigo'=>'06','departamento_id'=>'3'],
    ['id'=>'32','nombre'=>'San Bartolomé Milpas Altas','codigo'=>'07','departamento_id'=>'3'],
    ['id'=>'33','nombre'=>'San Lucas Sacatepéquez','codigo'=>'08','departamento_id'=>'3'],
    ['id'=>'34','nombre'=>'Santa Lucía Milpas Altas','codigo'=>'09','departamento_id'=>'3'],
    ['id'=>'35','nombre'=>'Magdalena Milpas Altas','codigo'=>'10','departamento_id'=>'3'],
    ['id'=>'36','nombre'=>'Santa María de Jesús','codigo'=>'11','departamento_id'=>'3'],
    ['id'=>'37','nombre'=>'Ciudad Vieja','codigo'=>'12','departamento_id'=>'3'],
    ['id'=>'38','nombre'=>'San Miguel Dueñas','codigo'=>'13','departamento_id'=>'3'],
    ['id'=>'39','nombre'=>'Alotenango','codigo'=>'14','departamento_id'=>'3'],
    ['id'=>'40','nombre'=>'San Antonio Aguas Calientes','codigo'=>'15','departamento_id'=>'3'],
    ['id'=>'41','nombre'=>'Santa Catarina Barahona','codigo'=>'16','departamento_id'=>'3'],
    ['id'=>'42','nombre'=>'Chimaltenango','codigo'=>'01','departamento_id'=>'4'],
    ['id'=>'43','nombre'=>'San José Poaquil','codigo'=>'02','departamento_id'=>'4'],
    ['id'=>'44','nombre'=>'San Martín Jilotepeque','codigo'=>'03','departamento_id'=>'4'],
    ['id'=>'45','nombre'=>'Comalapa','codigo'=>'04','departamento_id'=>'4'],
    ['id'=>'46','nombre'=>'Santa Apolonia','codigo'=>'05','departamento_id'=>'4'],
    ['id'=>'47','nombre'=>'Tecpán Guatemala','codigo'=>'06','departamento_id'=>'4'],
    ['id'=>'48','nombre'=>'Patzún','codigo'=>'07','departamento_id'=>'4'],
    ['id'=>'49','nombre'=>'Pochuta','codigo'=>'08','departamento_id'=>'4'],
    ['id'=>'50','nombre'=>'Patzicía','codigo'=>'09','departamento_id'=>'4'],
    ['id'=>'51','nombre'=>'Santa Cruz Balanyá','codigo'=>'10','departamento_id'=>'4'],
    ['id'=>'52','nombre'=>'Acatenango','codigo'=>'11','departamento_id'=>'4'],
    ['id'=>'53','nombre'=>'Yepocapa','codigo'=>'12','departamento_id'=>'4'],
    ['id'=>'54','nombre'=>'San Andrés Itzapa','codigo'=>'13','departamento_id'=>'4'],
    ['id'=>'55','nombre'=>'Parramos','codigo'=>'14','departamento_id'=>'4'],
    ['id'=>'56','nombre'=>'Zaragoza','codigo'=>'15','departamento_id'=>'4'],
    ['id'=>'57','nombre'=>'El Tejar','codigo'=>'16','departamento_id'=>'4'],
    ['id'=>'58','nombre'=>'Escuintla','codigo'=>'01','departamento_id'=>'5'],
    ['id'=>'59','nombre'=>'Santa Lucía Cotzumalguapa','codigo'=>'02','departamento_id'=>'5'],
    ['id'=>'60','nombre'=>'La Democracia','codigo'=>'03','departamento_id'=>'5'],
    ['id'=>'61','nombre'=>'Siquinalá','codigo'=>'04','departamento_id'=>'5'],
    ['id'=>'62','nombre'=>'Masagua','codigo'=>'05','departamento_id'=>'5'],
    ['id'=>'63','nombre'=>'Tiquisate','codigo'=>'06','departamento_id'=>'5'],
    ['id'=>'64','nombre'=>'La Gomera','codigo'=>'07','departamento_id'=>'5'],
    ['id'=>'65','nombre'=>'Guanagazapa','codigo'=>'08','departamento_id'=>'5'],
    ['id'=>'66','nombre'=>'San José','codigo'=>'09','departamento_id'=>'5'],
    ['id'=>'67','nombre'=>'Iztapa','codigo'=>'10','departamento_id'=>'5'],
    ['id'=>'68','nombre'=>'Palín','codigo'=>'11','departamento_id'=>'5'],
    ['id'=>'69','nombre'=>'San Vicente Pacaya','codigo'=>'12','departamento_id'=>'5'],
    ['id'=>'70','nombre'=>'Nueva Concepción','codigo'=>'13','departamento_id'=>'5'],
    ['id'=>'71','nombre'=>'Cuilapa','codigo'=>'01','departamento_id'=>'6'],
    ['id'=>'72','nombre'=>'Barberena','codigo'=>'02','departamento_id'=>'6'],
    ['id'=>'73','nombre'=>'Santa Rosa de Lima','codigo'=>'03','departamento_id'=>'6'],
    ['id'=>'74','nombre'=>'Casillas','codigo'=>'04','departamento_id'=>'6'],
    ['id'=>'75','nombre'=>'San Rafael las Flores','codigo'=>'05','departamento_id'=>'6'],
    ['id'=>'76','nombre'=>'Oratorio','codigo'=>'06','departamento_id'=>'6'],
    ['id'=>'77','nombre'=>'San Juan Tecuaco','codigo'=>'07','departamento_id'=>'6'],
    ['id'=>'78','nombre'=>'Chiquimulilla','codigo'=>'08','departamento_id'=>'6'],
    ['id'=>'79','nombre'=>'Taxisco','codigo'=>'09','departamento_id'=>'6'],
    ['id'=>'80','nombre'=>'Santa María Ixhuatán','codigo'=>'10','departamento_id'=>'6'],
    ['id'=>'81','nombre'=>'Guazacapán','codigo'=>'11','departamento_id'=>'6'],
    ['id'=>'82','nombre'=>'Santa Cruz Naranjo','codigo'=>'12','departamento_id'=>'6'],
    ['id'=>'83','nombre'=>'Pueblo Nuevo Viñas','codigo'=>'13','departamento_id'=>'6'],
    ['id'=>'84','nombre'=>'Nueva Santa Rosa','codigo'=>'14','departamento_id'=>'6'],
    ['id'=>'85','nombre'=>'Sololá','codigo'=>'01','departamento_id'=>'7'],
    ['id'=>'86','nombre'=>'San José Chacayá','codigo'=>'02','departamento_id'=>'7'],
    ['id'=>'87','nombre'=>'Santa María Visitación','codigo'=>'03','departamento_id'=>'7'],
    ['id'=>'88','nombre'=>'Santa Lucía Utatlán','codigo'=>'04','departamento_id'=>'7'],
    ['id'=>'89','nombre'=>'Nahualá','codigo'=>'05','departamento_id'=>'7'],
    ['id'=>'90','nombre'=>'Santa Catarina Ixtahuacán','codigo'=>'06','departamento_id'=>'7'],
    ['id'=>'91','nombre'=>'Santa Clara la Laguna','codigo'=>'07','departamento_id'=>'7'],
    ['id'=>'92','nombre'=>'Concepción','codigo'=>'08','departamento_id'=>'7'],
    ['id'=>'93','nombre'=>'San Andrés Semetabaj','codigo'=>'09','departamento_id'=>'7'],
    ['id'=>'94','nombre'=>'Panajachel','codigo'=>'10','departamento_id'=>'7'],
    ['id'=>'95','nombre'=>'Santa Catarina Palopó','codigo'=>'11','departamento_id'=>'7'],
    ['id'=>'96','nombre'=>'San Antonio Palopó','codigo'=>'12','departamento_id'=>'7'],
    ['id'=>'97','nombre'=>'San Lucas Tolimán','codigo'=>'13','departamento_id'=>'7'],
    ['id'=>'98','nombre'=>'Santa Cruz la Laguna','codigo'=>'14','departamento_id'=>'7'],
    ['id'=>'99','nombre'=>'San Pablo la Laguna','codigo'=>'15','departamento_id'=>'7'],
    ['id'=>'100','nombre'=>'San Marcos la Laguna','codigo'=>'16','departamento_id'=>'7'],
    ['id'=>'101','nombre'=>'San Juan la Laguna','codigo'=>'17','departamento_id'=>'7'],
    ['id'=>'102','nombre'=>'San Pedro la Laguna','codigo'=>'18','departamento_id'=>'7'],
    ['id'=>'103','nombre'=>'Santiago Atitlán','codigo'=>'19','departamento_id'=>'7'],
    ['id'=>'104','nombre'=>'Totonicapán','codigo'=>'01','departamento_id'=>'8'],
    ['id'=>'105','nombre'=>'San Cristóbal Totonicapán','codigo'=>'02','departamento_id'=>'8'],
    ['id'=>'106','nombre'=>'San Francisco el Alto','codigo'=>'03','departamento_id'=>'8'],
    ['id'=>'107','nombre'=>'San Andrés Xecul','codigo'=>'04','departamento_id'=>'8'],
    ['id'=>'108','nombre'=>'Momostenango','codigo'=>'05','departamento_id'=>'8'],
    ['id'=>'109','nombre'=>'Santa María Chiquimula','codigo'=>'06','departamento_id'=>'8'],
    ['id'=>'110','nombre'=>'Santa Lucía la Reforma','codigo'=>'07','departamento_id'=>'8'],
    ['id'=>'111','nombre'=>'San Bartolo','codigo'=>'08','departamento_id'=>'8'],
    ['id'=>'112','nombre'=>'Quetzaltenango','codigo'=>'01','departamento_id'=>'9'],
    ['id'=>'113','nombre'=>'Salcajá','codigo'=>'02','departamento_id'=>'9'],
    ['id'=>'114','nombre'=>'Olintepeque','codigo'=>'03','departamento_id'=>'9'],
    ['id'=>'115','nombre'=>'San Carlos Sija','codigo'=>'04','departamento_id'=>'9'],
    ['id'=>'116','nombre'=>'Sibilia','codigo'=>'05','departamento_id'=>'9'],
    ['id'=>'117','nombre'=>'Cabricán','codigo'=>'06','departamento_id'=>'9'],
    ['id'=>'118','nombre'=>'Cajolá','codigo'=>'07','departamento_id'=>'9'],
    ['id'=>'119','nombre'=>'San Miguel Siguilá','codigo'=>'08','departamento_id'=>'9'],
    ['id'=>'120','nombre'=>'Ostuncalco','codigo'=>'09','departamento_id'=>'9'],
    ['id'=>'121','nombre'=>'San Mateo','codigo'=>'10','departamento_id'=>'9'],
    ['id'=>'122','nombre'=>'Concepción Chiquirichapa','codigo'=>'11','departamento_id'=>'9'],
    ['id'=>'123','nombre'=>'San Martín Sacatepéquez','codigo'=>'12','departamento_id'=>'9'],
    ['id'=>'124','nombre'=>'Almolonga','codigo'=>'13','departamento_id'=>'9'],
    ['id'=>'125','nombre'=>'Cantel','codigo'=>'14','departamento_id'=>'9'],
    ['id'=>'126','nombre'=>'Huitán','codigo'=>'15','departamento_id'=>'9'],
    ['id'=>'127','nombre'=>'Zunil','codigo'=>'16','departamento_id'=>'9'],
    ['id'=>'128','nombre'=>'Colomba','codigo'=>'17','departamento_id'=>'9'],
    ['id'=>'129','nombre'=>'San Francisco la Unión','codigo'=>'18','departamento_id'=>'9'],
    ['id'=>'130','nombre'=>'El Palmar','codigo'=>'19','departamento_id'=>'9'],
    ['id'=>'131','nombre'=>'Coatepeque','codigo'=>'20','departamento_id'=>'9'],
    ['id'=>'132','nombre'=>'Génova','codigo'=>'21','departamento_id'=>'9'],
    ['id'=>'133','nombre'=>'Flores Costa Cuca','codigo'=>'22','departamento_id'=>'9'],
    ['id'=>'134','nombre'=>'La Esperanza','codigo'=>'23','departamento_id'=>'9'],
    ['id'=>'135','nombre'=>'Palestina de los Altos','codigo'=>'24','departamento_id'=>'9'],
    ['id'=>'136','nombre'=>'Mazatenango','codigo'=>'01','departamento_id'=>'10'],
    ['id'=>'137','nombre'=>'Cuyotenango','codigo'=>'02','departamento_id'=>'10'],
    ['id'=>'138','nombre'=>'San Francisco Zapotitlán','codigo'=>'03','departamento_id'=>'10'],
    ['id'=>'139','nombre'=>'San Bernardino','codigo'=>'04','departamento_id'=>'10'],
    ['id'=>'140','nombre'=>'San José el Idolo','codigo'=>'05','departamento_id'=>'10'],
    ['id'=>'141','nombre'=>'Santo Domingo Suchitepéquez','codigo'=>'06','departamento_id'=>'10'],
    ['id'=>'142','nombre'=>'San Lorenzo','codigo'=>'07','departamento_id'=>'10'],
    ['id'=>'143','nombre'=>'Samayac','codigo'=>'08','departamento_id'=>'10'],
    ['id'=>'144','nombre'=>'San Pablo Jocopilas','codigo'=>'09','departamento_id'=>'10'],
    ['id'=>'145','nombre'=>'San Antonio Suchitepéquez','codigo'=>'10','departamento_id'=>'10'],
    ['id'=>'146','nombre'=>'San Miguel Panán','codigo'=>'11','departamento_id'=>'10'],
    ['id'=>'147','nombre'=>'San Gabriel','codigo'=>'12','departamento_id'=>'10'],
    ['id'=>'148','nombre'=>'Chicacao','codigo'=>'13','departamento_id'=>'10'],
    ['id'=>'149','nombre'=>'Patulul','codigo'=>'14','departamento_id'=>'10'],
    ['id'=>'150','nombre'=>'Santa Bárbara','codigo'=>'15','departamento_id'=>'10'],
    ['id'=>'151','nombre'=>'San Juan Bautista','codigo'=>'16','departamento_id'=>'10'],
    ['id'=>'152','nombre'=>'Santo Tomás la Unión','codigo'=>'17','departamento_id'=>'10'],
    ['id'=>'153','nombre'=>'Zunilito','codigo'=>'18','departamento_id'=>'10'],
    ['id'=>'154','nombre'=>'Pueblo Nuevo','codigo'=>'19','departamento_id'=>'10'],
    ['id'=>'155','nombre'=>'Río Bravo','codigo'=>'20','departamento_id'=>'10'],
    ['id'=>'156','nombre'=>'San José La Máquina','codigo'=>'21','departamento_id'=>'10'],
    ['id'=>'157','nombre'=>'Retalhuleu','codigo'=>'01','departamento_id'=>'11'],
    ['id'=>'158','nombre'=>'San Sebastián','codigo'=>'02','departamento_id'=>'11'],
    ['id'=>'159','nombre'=>'Santa Cruz Muluá','codigo'=>'03','departamento_id'=>'11'],
    ['id'=>'160','nombre'=>'San Martín Zapotitlán','codigo'=>'04','departamento_id'=>'11'],
    ['id'=>'161','nombre'=>'San Felipe','codigo'=>'05','departamento_id'=>'11'],
    ['id'=>'162','nombre'=>'San Andrés Villa Seca','codigo'=>'06','departamento_id'=>'11'],
    ['id'=>'163','nombre'=>'Champerico','codigo'=>'07','departamento_id'=>'11'],
    ['id'=>'164','nombre'=>'Nuevo San Carlos','codigo'=>'08','departamento_id'=>'11'],
    ['id'=>'165','nombre'=>'El Asintal','codigo'=>'09','departamento_id'=>'11'],
    ['id'=>'166','nombre'=>'San Marcos','codigo'=>'01','departamento_id'=>'12'],
    ['id'=>'167','nombre'=>'San Pedro Sacatepéquez','codigo'=>'02','departamento_id'=>'12'],
    ['id'=>'168','nombre'=>'San Antonio Sacatepéquez','codigo'=>'03','departamento_id'=>'12'],
    ['id'=>'169','nombre'=>'Comitancillo','codigo'=>'04','departamento_id'=>'12'],
    ['id'=>'170','nombre'=>'San Miguel Ixtahuacán','codigo'=>'05','departamento_id'=>'12'],
    ['id'=>'171','nombre'=>'Concepción Tutuapa','codigo'=>'06','departamento_id'=>'12'],
    ['id'=>'172','nombre'=>'Tacaná','codigo'=>'07','departamento_id'=>'12'],
    ['id'=>'173','nombre'=>'Sibinal','codigo'=>'08','departamento_id'=>'12'],
    ['id'=>'174','nombre'=>'Tajumulco','codigo'=>'09','departamento_id'=>'12'],
    ['id'=>'175','nombre'=>'Tejutla','codigo'=>'10','departamento_id'=>'12'],
    ['id'=>'176','nombre'=>'San Rafael Pié de la Cuesta','codigo'=>'11','departamento_id'=>'12'],
    ['id'=>'177','nombre'=>'Nuevo Progreso','codigo'=>'12','departamento_id'=>'12'],
    ['id'=>'178','nombre'=>'El Tumbador','codigo'=>'13','departamento_id'=>'12'],
    ['id'=>'179','nombre'=>'El Rodeo','codigo'=>'14','departamento_id'=>'12'],
    ['id'=>'180','nombre'=>'Malacatán','codigo'=>'15','departamento_id'=>'12'],
    ['id'=>'181','nombre'=>'Catarina','codigo'=>'16','departamento_id'=>'12'],
    ['id'=>'182','nombre'=>'Ayutla','codigo'=>'17','departamento_id'=>'12'],
    ['id'=>'183','nombre'=>'Ocós','codigo'=>'18','departamento_id'=>'12'],
    ['id'=>'184','nombre'=>'San Pablo','codigo'=>'19','departamento_id'=>'12'],
    ['id'=>'185','nombre'=>'El Quetzal','codigo'=>'20','departamento_id'=>'12'],
    ['id'=>'186','nombre'=>'La Reforma','codigo'=>'21','departamento_id'=>'12'],
    ['id'=>'187','nombre'=>'Pajapita','codigo'=>'22','departamento_id'=>'12'],
    ['id'=>'188','nombre'=>'Ixchiguán','codigo'=>'23','departamento_id'=>'12'],
    ['id'=>'189','nombre'=>'San José Ojetenán','codigo'=>'24','departamento_id'=>'12'],
    ['id'=>'190','nombre'=>'San Cristóbal Cucho','codigo'=>'25','departamento_id'=>'12'],
    ['id'=>'191','nombre'=>'Sipacapa','codigo'=>'26','departamento_id'=>'12'],
    ['id'=>'192','nombre'=>'Esquipulas Palo Gordo','codigo'=>'27','departamento_id'=>'12'],
    ['id'=>'193','nombre'=>'Río Blanco','codigo'=>'28','departamento_id'=>'12'],
    ['id'=>'194','nombre'=>'San Lorenzo','codigo'=>'29','departamento_id'=>'12'],
    ['id'=>'195','nombre'=>'La Blanca','codigo'=>'30','departamento_id'=>'12'],
    ['id'=>'196','nombre'=>'Huehuetenango','codigo'=>'01','departamento_id'=>'13'],
    ['id'=>'197','nombre'=>'Chiantla','codigo'=>'02','departamento_id'=>'13'],
    ['id'=>'198','nombre'=>'Malacatancito','codigo'=>'03','departamento_id'=>'13'],
    ['id'=>'199','nombre'=>'Cuilco','codigo'=>'04','departamento_id'=>'13'],
    ['id'=>'200','nombre'=>'Nentón','codigo'=>'05','departamento_id'=>'13'],
    ['id'=>'201','nombre'=>'San Pedro Necta','codigo'=>'06','departamento_id'=>'13'],
    ['id'=>'202','nombre'=>'Jacaltenango','codigo'=>'07','departamento_id'=>'13'],
    ['id'=>'203','nombre'=>'Soloma','codigo'=>'08','departamento_id'=>'13'],
    ['id'=>'204','nombre'=>'Ixtahuacán','codigo'=>'09','departamento_id'=>'13'],
    ['id'=>'205','nombre'=>'Santa Bárbara','codigo'=>'10','departamento_id'=>'13'],
    ['id'=>'206','nombre'=>'La Libertad','codigo'=>'11','departamento_id'=>'13'],
    ['id'=>'207','nombre'=>'La Democracia','codigo'=>'12','departamento_id'=>'13'],
    ['id'=>'208','nombre'=>'San Miguel Acatán','codigo'=>'13','departamento_id'=>'13'],
    ['id'=>'209','nombre'=>'San Rafael la Independencia','codigo'=>'14','departamento_id'=>'13'],
    ['id'=>'210','nombre'=>'Todos Santos Cuchumatán','codigo'=>'15','departamento_id'=>'13'],
    ['id'=>'211','nombre'=>'San Juan Atitán','codigo'=>'16','departamento_id'=>'13'],
    ['id'=>'212','nombre'=>'Santa Eulalia','codigo'=>'17','departamento_id'=>'13'],
    ['id'=>'213','nombre'=>'San Mateo Ixtatán','codigo'=>'18','departamento_id'=>'13'],
    ['id'=>'214','nombre'=>'Colotenango','codigo'=>'19','departamento_id'=>'13'],
    ['id'=>'215','nombre'=>'San Sebastián Huehuetenango','codigo'=>'20','departamento_id'=>'13'],
    ['id'=>'216','nombre'=>'Tectitán','codigo'=>'21','departamento_id'=>'13'],
    ['id'=>'217','nombre'=>'Concepción Huista','codigo'=>'22','departamento_id'=>'13'],
    ['id'=>'218','nombre'=>'San Juan Ixcoy','codigo'=>'23','departamento_id'=>'13'],
    ['id'=>'219','nombre'=>'San Antonio Huista','codigo'=>'24','departamento_id'=>'13'],
    ['id'=>'220','nombre'=>'San Sebastián Coatán','codigo'=>'25','departamento_id'=>'13'],
    ['id'=>'221','nombre'=>'Barillas','codigo'=>'26','departamento_id'=>'13'],
    ['id'=>'222','nombre'=>'Aguacatán','codigo'=>'27','departamento_id'=>'13'],
    ['id'=>'223','nombre'=>'San Rafael Petzal','codigo'=>'28','departamento_id'=>'13'],
    ['id'=>'224','nombre'=>'San Gaspar Ixchil','codigo'=>'29','departamento_id'=>'13'],
    ['id'=>'225','nombre'=>'Santiago Chimaltenango','codigo'=>'30','departamento_id'=>'13'],
    ['id'=>'226','nombre'=>'Santa Ana Huista','codigo'=>'31','departamento_id'=>'13'],
    ['id'=>'227','nombre'=>'Unión Cantinil','codigo'=>'32','departamento_id'=>'13'],
    ['id'=>'228','nombre'=>'Santa Cruz del Quiché','codigo'=>'01','departamento_id'=>'14'],
    ['id'=>'229','nombre'=>'Chiché','codigo'=>'02','departamento_id'=>'14'],
    ['id'=>'230','nombre'=>'Chinique','codigo'=>'03','departamento_id'=>'14'],
    ['id'=>'231','nombre'=>'Zacualpa','codigo'=>'04','departamento_id'=>'14'],
    ['id'=>'232','nombre'=>'Chajul','codigo'=>'05','departamento_id'=>'14'],
    ['id'=>'233','nombre'=>'Chichicastenango','codigo'=>'06','departamento_id'=>'14'],
    ['id'=>'234','nombre'=>'Patzité','codigo'=>'07','departamento_id'=>'14'],
    ['id'=>'235','nombre'=>'San Antonio Ilotenango','codigo'=>'08','departamento_id'=>'14'],
    ['id'=>'236','nombre'=>'San Pedro Jocopilas','codigo'=>'09','departamento_id'=>'14'],
    ['id'=>'237','nombre'=>'Cunén','codigo'=>'10','departamento_id'=>'14'],
    ['id'=>'238','nombre'=>'San Juan Cotzal','codigo'=>'11','departamento_id'=>'14'],
    ['id'=>'239','nombre'=>'Joyabaj','codigo'=>'12','departamento_id'=>'14'],
    ['id'=>'240','nombre'=>'Nebaj','codigo'=>'13','departamento_id'=>'14'],
    ['id'=>'241','nombre'=>'San Andrés Sajcabajá','codigo'=>'14','departamento_id'=>'14'],
    ['id'=>'242','nombre'=>'Uspantán','codigo'=>'15','departamento_id'=>'14'],
    ['id'=>'243','nombre'=>'Sacapulas','codigo'=>'16','departamento_id'=>'14'],
    ['id'=>'244','nombre'=>'San Bartolomé Jocotenango','codigo'=>'17','departamento_id'=>'14'],
    ['id'=>'245','nombre'=>'Canillá','codigo'=>'18','departamento_id'=>'14'],
    ['id'=>'246','nombre'=>'Chicamán','codigo'=>'19','departamento_id'=>'14'],
    ['id'=>'247','nombre'=>'Ixcán','codigo'=>'20','departamento_id'=>'14'],
    ['id'=>'248','nombre'=>'Pachalum','codigo'=>'21','departamento_id'=>'14'],
    ['id'=>'249','nombre'=>'Salamá','codigo'=>'01','departamento_id'=>'15'],
    ['id'=>'250','nombre'=>'San Miguel Chicaj','codigo'=>'02','departamento_id'=>'15'],
    ['id'=>'251','nombre'=>'Rabinal','codigo'=>'03','departamento_id'=>'15'],
    ['id'=>'252','nombre'=>'Cubulco','codigo'=>'04','departamento_id'=>'15'],
    ['id'=>'253','nombre'=>'Granados','codigo'=>'05','departamento_id'=>'15'],
    ['id'=>'254','nombre'=>'El Chol','codigo'=>'06','departamento_id'=>'15'],
    ['id'=>'255','nombre'=>'San Jerónimo','codigo'=>'07','departamento_id'=>'15'],
    ['id'=>'256','nombre'=>'Purulhá','codigo'=>'08','departamento_id'=>'15'],
    ['id'=>'257','nombre'=>'Cobán','codigo'=>'01','departamento_id'=>'16'],
    ['id'=>'258','nombre'=>'Santa Cruz Verapaz','codigo'=>'02','departamento_id'=>'16'],
    ['id'=>'259','nombre'=>'San Cristóbal Verapaz','codigo'=>'03','departamento_id'=>'16'],
    ['id'=>'260','nombre'=>'Tactic','codigo'=>'04','departamento_id'=>'16'],
    ['id'=>'261','nombre'=>'Tamahú','codigo'=>'05','departamento_id'=>'16'],
    ['id'=>'262','nombre'=>'Tucurú','codigo'=>'06','departamento_id'=>'16'],
    ['id'=>'263','nombre'=>'Panzós','codigo'=>'07','departamento_id'=>'16'],
    ['id'=>'264','nombre'=>'Senahú','codigo'=>'08','departamento_id'=>'16'],
    ['id'=>'265','nombre'=>'San Pedro Carchá','codigo'=>'09','departamento_id'=>'16'],
    ['id'=>'266','nombre'=>'San Juan Chamelco','codigo'=>'10','departamento_id'=>'16'],
    ['id'=>'267','nombre'=>'Lanquín','codigo'=>'11','departamento_id'=>'16'],
    ['id'=>'268','nombre'=>'Cahabón','codigo'=>'12','departamento_id'=>'16'],
    ['id'=>'269','nombre'=>'Chisec','codigo'=>'13','departamento_id'=>'16'],
    ['id'=>'270','nombre'=>'Chahal','codigo'=>'14','departamento_id'=>'16'],
    ['id'=>'271','nombre'=>'Fray Bartolomé de las Casas','codigo'=>'15','departamento_id'=>'16'],
    ['id'=>'272','nombre'=>'Santa Catalina la Tinta','codigo'=>'16','departamento_id'=>'16'],
    ['id'=>'273','nombre'=>'Raxruhá','codigo'=>'17','departamento_id'=>'16'],
    ['id'=>'274','nombre'=>'Flores','codigo'=>'01','departamento_id'=>'17'],
    ['id'=>'275','nombre'=>'San José','codigo'=>'02','departamento_id'=>'17'],
    ['id'=>'276','nombre'=>'San Benito','codigo'=>'03','departamento_id'=>'17'],
    ['id'=>'277','nombre'=>'San Andrés','codigo'=>'04','departamento_id'=>'17'],
    ['id'=>'278','nombre'=>'La Libertad','codigo'=>'05','departamento_id'=>'17'],
    ['id'=>'279','nombre'=>'San Francisco','codigo'=>'06','departamento_id'=>'17'],
    ['id'=>'280','nombre'=>'Santa Ana','codigo'=>'07','departamento_id'=>'17'],
    ['id'=>'281','nombre'=>'Dolores','codigo'=>'08','departamento_id'=>'17'],
    ['id'=>'282','nombre'=>'San Luis','codigo'=>'09','departamento_id'=>'17'],
    ['id'=>'283','nombre'=>'Sayaxché','codigo'=>'10','departamento_id'=>'17'],
    ['id'=>'284','nombre'=>'Melchor de Mencos','codigo'=>'11','departamento_id'=>'17'],
    ['id'=>'285','nombre'=>'Poptún','codigo'=>'12','departamento_id'=>'17'],
    ['id'=>'286','nombre'=>'Las Cruces','codigo'=>'13','departamento_id'=>'17'],
    ['id'=>'287','nombre'=>'El Chal','codigo'=>'14','departamento_id'=>'17'],
    ['id'=>'288','nombre'=>'Puerto Barrios','codigo'=>'01','departamento_id'=>'18'],
    ['id'=>'289','nombre'=>'Livingston','codigo'=>'02','departamento_id'=>'18'],
    ['id'=>'290','nombre'=>'El Estor','codigo'=>'03','departamento_id'=>'18'],
    ['id'=>'291','nombre'=>'Morales','codigo'=>'04','departamento_id'=>'18'],
    ['id'=>'292','nombre'=>'Los Amates','codigo'=>'05','departamento_id'=>'18'],
    ['id'=>'293','nombre'=>'Zacapa','codigo'=>'01','departamento_id'=>'19'],
    ['id'=>'294','nombre'=>'Estanzuela','codigo'=>'02','departamento_id'=>'19'],
    ['id'=>'295','nombre'=>'Río Hondo','codigo'=>'03','departamento_id'=>'19'],
    ['id'=>'296','nombre'=>'Gualán','codigo'=>'04','departamento_id'=>'19'],
    ['id'=>'297','nombre'=>'Teculután','codigo'=>'05','departamento_id'=>'19'],
    ['id'=>'298','nombre'=>'Usumatlán','codigo'=>'06','departamento_id'=>'19'],
    ['id'=>'299','nombre'=>'Cabañas','codigo'=>'07','departamento_id'=>'19'],
    ['id'=>'300','nombre'=>'San Diego','codigo'=>'08','departamento_id'=>'19'],
    ['id'=>'301','nombre'=>'La Unión','codigo'=>'09','departamento_id'=>'19'],
    ['id'=>'302','nombre'=>'Huité','codigo'=>'10','departamento_id'=>'19'],
    ['id'=>'303','nombre'=>'San Jorge','codigo'=>'11','departamento_id'=>'19'],
    ['id'=>'304','nombre'=>'Chiquimula','codigo'=>'01','departamento_id'=>'20'],
    ['id'=>'305','nombre'=>'San José La Arada','codigo'=>'02','departamento_id'=>'20'],
    ['id'=>'306','nombre'=>'San Juan Ermita','codigo'=>'03','departamento_id'=>'20'],
    ['id'=>'307','nombre'=>'Jocotán','codigo'=>'04','departamento_id'=>'20'],
    ['id'=>'308','nombre'=>'Camotán','codigo'=>'05','departamento_id'=>'20'],
    ['id'=>'309','nombre'=>'Olopa','codigo'=>'06','departamento_id'=>'20'],
    ['id'=>'310','nombre'=>'Esquipulas','codigo'=>'07','departamento_id'=>'20'],
    ['id'=>'311','nombre'=>'Concepción Las Minas','codigo'=>'08','departamento_id'=>'20'],
    ['id'=>'312','nombre'=>'Quetzaltepeque','codigo'=>'09','departamento_id'=>'20'],
    ['id'=>'313','nombre'=>'San Jacinto','codigo'=>'10','departamento_id'=>'20'],
    ['id'=>'314','nombre'=>'Ipala','codigo'=>'11','departamento_id'=>'20'],
    ['id'=>'315','nombre'=>'Jalapa','codigo'=>'01','departamento_id'=>'21'],
    ['id'=>'316','nombre'=>'San Pedro Pinula','codigo'=>'02','departamento_id'=>'21'],
    ['id'=>'317','nombre'=>'San Luis Jilotepeque','codigo'=>'03','departamento_id'=>'21'],
    ['id'=>'318','nombre'=>'San Manuel Chaparrón','codigo'=>'04','departamento_id'=>'21'],
    ['id'=>'319','nombre'=>'San Carlos Alzatate','codigo'=>'05','departamento_id'=>'21'],
    ['id'=>'320','nombre'=>'Monjas','codigo'=>'06','departamento_id'=>'21'],
    ['id'=>'321','nombre'=>'Mataquescuintla','codigo'=>'07','departamento_id'=>'21'],
    ['id'=>'322','nombre'=>'Jutiapa','codigo'=>'01','departamento_id'=>'22'],
    ['id'=>'323','nombre'=>'El Progreso','codigo'=>'02','departamento_id'=>'22'],
    ['id'=>'324','nombre'=>'Santa Catarina Mita','codigo'=>'03','departamento_id'=>'22'],
    ['id'=>'325','nombre'=>'Agua Blanca','codigo'=>'04','departamento_id'=>'22'],
    ['id'=>'326','nombre'=>'Asunción Mita','codigo'=>'05','departamento_id'=>'22'],
    ['id'=>'327','nombre'=>'Yupiltepeque','codigo'=>'06','departamento_id'=>'22'],
    ['id'=>'328','nombre'=>'Atescatempa','codigo'=>'07','departamento_id'=>'22'],
    ['id'=>'329','nombre'=>'Jerez','codigo'=>'08','departamento_id'=>'22'],
    ['id'=>'330','nombre'=>'El Adelanto','codigo'=>'09','departamento_id'=>'22'],
    ['id'=>'331','nombre'=>'Zapotitlán','codigo'=>'10','departamento_id'=>'22'],
    ['id'=>'332','nombre'=>'Comapa','codigo'=>'11','departamento_id'=>'22'],
    ['id'=>'333','nombre'=>'Jalpatagua','codigo'=>'12','departamento_id'=>'22'],
    ['id'=>'334','nombre'=>'Conguaco','codigo'=>'13','departamento_id'=>'22'],
    ['id'=>'335','nombre'=>'Moyuta','codigo'=>'14','departamento_id'=>'22'],
    ['id'=>'336','nombre'=>'Pasaco','codigo'=>'15','departamento_id'=>'22'],
    ['id'=>'337','nombre'=>'San José Acatempa','codigo'=>'16','departamento_id'=>'22'],
    ['id'=>'338','nombre'=>'Quesada','codigo'=>'17','departamento_id'=>'22'],



];
}
