<?php
/** frk */
namespace App\Constantes;

class VehiculoData
{


public static $tipo_placa = [
    ['id'=>'1','nombre'=>'P-Particular','valor'=>'P'],
    ['id'=>'2','nombre'=>'C-Comercial, Extraurbano, carga y Escolar','valor'=>'C'],
    ['id'=>'3','nombre'=>'O-Oficial','valor'=>'O'],
    ['id'=>'4','nombre'=>'U-Urbano','valor'=>'U'],
    ['id'=>'5','nombre'=>'TCR-Agricola, Industria o Construccion','valor'=>'TCR'],
    ['id'=>'6','nombre'=>'M-Moto','valor'=>'M'],
    ['id'=>'7','nombre'=>'A-Alquiler','valor'=>'A'],
];


public static $tipo_vehiculo = [
    ['id'=>'1','nombre'=>'Motocicleta'],
    ['id'=>'2','nombre'=>'Automovil'],
    ['id'=>'3','nombre'=>'Panel'],
    ['id'=>'4','nombre'=>'Pick-up'],
    ['id'=>'5','nombre'=>'Microbus'],
    ['id'=>'6','nombre'=>'Camion'],
    ['id'=>'7','nombre'=>'Cabezal'],
    ['id'=>'8','nombre'=>'Agricola'],
];

public static $marca_vehiculo = [
    ['id'=>'1','nombre'=>'Abarth'],
    ['id'=>'2','nombre'=>'Alfa Romeo'],
    ['id'=>'3','nombre'=>'Aro'],
    ['id'=>'4','nombre'=>'Asia'],
    ['id'=>'5','nombre'=>'Asia Motors'],
    ['id'=>'6','nombre'=>'Aston Martin'],
    ['id'=>'7','nombre'=>'Audi'],
    ['id'=>'8','nombre'=>'Austin'],
    ['id'=>'9','nombre'=>'Auverland'],
    ['id'=>'10','nombre'=>'Baic'],
    ['id'=>'11','nombre'=>'Bentley'],
    ['id'=>'12','nombre'=>'Bertone'],
    ['id'=>'13','nombre'=>'Bmw'],
    ['id'=>'14','nombre'=>'BYD'],
    ['id'=>'15','nombre'=>'Cadillac'],
    ['id'=>'16','nombre'=>'Changan'],
    ['id'=>'17','nombre'=>'Chevrolet'],
    ['id'=>'18','nombre'=>'Chirey'],
    ['id'=>'19','nombre'=>'Chrysler'],
    ['id'=>'20','nombre'=>'Citroen'],
    ['id'=>'21','nombre'=>'Corvette'],
    ['id'=>'22','nombre'=>'Dacia'],
    ['id'=>'23','nombre'=>'Daewoo'],
    ['id'=>'24','nombre'=>'Daf'],
    ['id'=>'25','nombre'=>'Daihatsu'],
    ['id'=>'26','nombre'=>'Daimler'],
    ['id'=>'27','nombre'=>'Dodge'],
    ['id'=>'28','nombre'=>'Foton'],
    ['id'=>'29','nombre'=>'Ferrari'],
    ['id'=>'30','nombre'=>'Fiat'],
    ['id'=>'31','nombre'=>'Ford'],
    ['id'=>'32','nombre'=>'Galloper'],
    ['id'=>'33','nombre'=>'Gmc'],
    ['id'=>'34','nombre'=>'Hino'],
    ['id'=>'35','nombre'=>'Honda'],
    ['id'=>'36','nombre'=>'Hummer'],
    ['id'=>'37','nombre'=>'Hyundai'],
    ['id'=>'38','nombre'=>'Infiniti'],
    ['id'=>'39','nombre'=>'Innocenti'],
    ['id'=>'40','nombre'=>'Isuzu'],
    ['id'=>'41','nombre'=>'Iveco'],
    ['id'=>'42','nombre'=>'Iveco-pegaso'],
    ['id'=>'43','nombre'=>'Jac'],
    ['id'=>'44','nombre'=>'Jaguar'],
    ['id'=>'45','nombre'=>'JMC'],
    ['id'=>'46','nombre'=>'Jeep'],
    ['id'=>'47','nombre'=>'Kia'],
    ['id'=>'48','nombre'=>'Lada'],
    ['id'=>'49','nombre'=>'Lamborghini'],
    ['id'=>'50','nombre'=>'Lancia'],
    ['id'=>'51','nombre'=>'Land-rover'],
    ['id'=>'52','nombre'=>'Ldv'],
    ['id'=>'53','nombre'=>'Lexus'],
    ['id'=>'54','nombre'=>'Lotus'],
    ['id'=>'55','nombre'=>'Mahindra'],
    ['id'=>'56','nombre'=>'Maserati'],
    ['id'=>'57','nombre'=>'Maybach'],
    ['id'=>'58','nombre'=>'Mazda'],
    ['id'=>'59','nombre'=>'Mercedes-benz'],
    ['id'=>'60','nombre'=>'Mg'],
    ['id'=>'61','nombre'=>'Mini'],
    ['id'=>'62','nombre'=>'Mitsubishi'],
    ['id'=>'63','nombre'=>'Morgan'],
    ['id'=>'64','nombre'=>'Nissan'],
    ['id'=>'65','nombre'=>'Opel'],
    ['id'=>'66','nombre'=>'Peugeot'],
    ['id'=>'67','nombre'=>'Pontiac'],
    ['id'=>'68','nombre'=>'Porsche'],
    ['id'=>'69','nombre'=>'Renault'],
    ['id'=>'70','nombre'=>'Rolls-royce'],
    ['id'=>'71','nombre'=>'Rover'],
    ['id'=>'72','nombre'=>'Saab'],
    ['id'=>'73','nombre'=>'Santana'],
    ['id'=>'74','nombre'=>'Scania'],
    ['id'=>'75','nombre'=>'Seat'],
    ['id'=>'76','nombre'=>'Skoda'],
    ['id'=>'77','nombre'=>'Smart'],
    ['id'=>'78','nombre'=>'Ssangyong'],
    ['id'=>'79','nombre'=>'Subaru'],
    ['id'=>'80','nombre'=>'Suzuki'],
    ['id'=>'81','nombre'=>'Talbot'],
    ['id'=>'82','nombre'=>'Tata'],
    ['id'=>'83','nombre'=>'Toyota'],
    ['id'=>'84','nombre'=>'Umm'],
    ['id'=>'85','nombre'=>'Vaz'],
    ['id'=>'86','nombre'=>'Volkswagen'],
    ['id'=>'87','nombre'=>'Volvo'],
    ['id'=>'88','nombre'=>'Wartburg'],

];

public static $modelo_vehiculo = [

['id'=>'1','nombre'=>'1980'],
['id'=>'2','nombre'=>'1981'],
['id'=>'3','nombre'=>'1982'],
['id'=>'4','nombre'=>'1983'],
['id'=>'5','nombre'=>'1984'],
['id'=>'6','nombre'=>'1985'],
['id'=>'7','nombre'=>'1986'],
['id'=>'8','nombre'=>'1987'],
['id'=>'9','nombre'=>'1988'],
['id'=>'10','nombre'=>'1989'],
['id'=>'11','nombre'=>'1990'],
['id'=>'12','nombre'=>'1991'],
['id'=>'13','nombre'=>'1992'],
['id'=>'14','nombre'=>'1993'],
['id'=>'15','nombre'=>'1994'],
['id'=>'16','nombre'=>'1995'],
['id'=>'17','nombre'=>'1996'],
['id'=>'18','nombre'=>'1997'],
['id'=>'19','nombre'=>'1998'],
['id'=>'20','nombre'=>'1999'],
['id'=>'21','nombre'=>'2000'],
['id'=>'22','nombre'=>'2001'],
['id'=>'23','nombre'=>'2002'],
['id'=>'24','nombre'=>'2003'],
['id'=>'25','nombre'=>'2004'],
['id'=>'26','nombre'=>'2005'],
['id'=>'27','nombre'=>'2006'],
['id'=>'28','nombre'=>'2007'],
['id'=>'29','nombre'=>'2008'],
['id'=>'30','nombre'=>'2009'],
['id'=>'31','nombre'=>'2010'],
['id'=>'32','nombre'=>'2011'],
['id'=>'33','nombre'=>'2012'],
['id'=>'34','nombre'=>'2013'],
['id'=>'35','nombre'=>'2014'],
['id'=>'36','nombre'=>'2015'],
['id'=>'37','nombre'=>'2016'],
['id'=>'38','nombre'=>'2017'],
['id'=>'39','nombre'=>'2018'],
['id'=>'40','nombre'=>'2019'],
['id'=>'41','nombre'=>'2020'],
['id'=>'42','nombre'=>'2021'],
['id'=>'43','nombre'=>'2022'],
['id'=>'44','nombre'=>'2023'],
];




}
